### ISSUE TITLE
Klines websocket pushing incorrect data, causing duplicate timestamps (affects all klines indicators)

### ISSUE THREAD

**Issue by LevBeta** [beatzxbt/bybit-smm#5]
Can you explain better this bug? I have been trying to repreduce it, but without any success until now!

**Comment by beatzxbt** [comment]
Uhh, neither can i...

The issue clearly existed for some time -> https://twitter.com/BeatzXBT/status/1702063950718750949

Now running and watching the code, it's working just fine (It's appended the previous 20 candles without issues). Previously, the duplicates would start even after 2 candles.

I'll leave the issue open incase the bug comes back, and close it in a few days if its working nominally. Certainly had to be an issue on Bybit's end, as code is unchanged on my end.

**Comment by beatzxbt** [comment]
Seems to be working fine, closing this.
